name: CI
on: [push]
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run unit tests
        run: npm run test
  functional-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run functional tests
        run: npm run functional